In [2]:
import numpy as np

In [3]:
# NUmpy data Types and Type casting
arr=np.array([1,2,3.1,4,'5'])
arr
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [5]:
#type casting 

arr=np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [6]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3., 4.])

In [7]:
new_arr1=new_arr.astype(np.int64)
new_arr1


array([1, 2, 3, 4], dtype=int64)

In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)


1
(4,)
4
4


In [9]:
# Arrray reshaping
arr=np.array([[1,3,4,],[2,3,4]])
reshaped=arr.reshape(3,2)
print(reshaped)

[[1 3]
 [4 2]
 [3 4]]


In [10]:
# ravel to covert into one d array of any dimension
ravel=arr.ravel()
ravel

array([1, 3, 4, 2, 3, 4])

In [25]:
ravel[1]=100
ravel

array([  1, 100,   4,   2,   3,   4])

In [12]:
arr

array([[1, 3, 4],
       [2, 3, 4]])

In [11]:
flat=ravel.flatten()
flat

array([1, 3, 4, 2, 3, 4])