In [2]:
import numpy as np

In [3]:
# aggregare functions
arr=np.array([1,2,3,4])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))


10
2.5
1.118033988749895
1.25
1
4


In [4]:

mat = np.array([[1,2,3],[4,5,6]])
print(np.sum(mat, axis=0))

[5 7 9]


In [5]:
#cumalative opeartions
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10]
[ 1  2  6 24]


In [11]:
arr

array([1, 2, 3, 4])

In [6]:
res=np.where(arr<2,"low","high")
print(res)

['low' 'high' 'high' 'high']


In [14]:
print(np.argwhere(arr>1))

[[1]
 [2]
 [3]]


In [16]:
# logical and
mask=np.logical_and(arr>3 ,arr<6)
print(mask)

[False False False  True]


In [17]:
mask=np.logical_or(arr<4,arr>5)
print(mask)

[ True  True  True False]


In [5]:
## Broad casting 
# streching the shape of the arr to match the shape of ther arr

a = np.array([1,2,3])
b = 2
a + b         # [3 4 5]


array([3, 4, 5])

In [7]:
## vectorization
# Instead of:
res = []
for x in range(1000000):
    res.append(x * 2)

# Use NumPy
arr = np.arange(1000000)
res = arr * 2
res

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])