In [1]:
!pip install numpy


In [2]:
import numpy as np
import time

# Using Python list
list1 = list(range(10))
start = time.time()
list_result = [x * 2 for x in list1]
print("List time:", time.time() - start)

# Using NumPy array
arr = np.arange(10)
start = time.time()

arr_result = arr * 2
print("NumPy time:", time.time() - start)


List time: 0.0009915828704833984
NumPy time: 0.0


In [4]:
a=[1,2,'a','gfhgjdkl']
np.array(a)

array(['1', '2', 'a', 'gfhgjdkl'], dtype='<U11')

In [10]:
arr=np.array([[1,2,3,4]])
arr.ndim
arr.shape

(1, 4)

In [ ]:
range=np.arange(1,10,2)  # start stop and step
range

array([1, 3, 5, 7, 9])

In [4]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
##logarrtimic scale arr
arr=np.logspace(1,3,3) # lograthimic scale arr 10^1 .....   starting power enging power scale value
arr

array([  10.,  100., 1000.])

In [ ]:
arr=np.zeros(5)   # arr full of zeroes
arr

arr1=np.zeros([3,3])  # 3 rowa and 3 cols
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr=np.full([2,4],7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
arr2=np.empty([2,3])  # unintialzed array
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr=np.random.rand(2,3)  # used to generate  floats
arr  

array([[0.67612729, 0.89873295, 0.40176139],
       [0.26194218, 0.76868262, 0.61901607]])

In [18]:
arr=np.random.randn(2,3) 
arr # this geenrate a nums whose mean=0 and sd=1

array([[ 0.46299296,  0.81969817, -1.81634428],
       [-0.22984234, -1.19549744,  0.70811504]])

In [23]:
arr=np.random.randint(1,100,size=(3,3))
arr


array([[83, 70, 29],
       [ 4, 74,  9],
       [35, 54, 73]])