In [10]:
# Arithemetic operations  on Arrays
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,4])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)
print(a**2)
print(b**2)

[2 4 6 8 9]
[0 0 0 0 1]
[1.   1.   1.   1.   1.25]
[ 1  4  9 16 20]
[1 1 1 1 1]
[0 0 0 0 1]
[  1   4  27 256 625]
[ 1  4  9 16 25]
[ 1  4  9 16 16]


In [11]:
# Universal functions
arr=np.array([1,3,5,9])
arr

array([1, 3, 5, 9])

In [12]:
sq=np.sqrt(arr)
print(sq)

[1.         1.73205081 2.23606798 3.        ]


In [15]:
# exponential
print(np.exp([1,2]))

# sine  function
ang=np.array([0,np.pi/2,np.pi])
print(np.sin(ang))

[2.71828183 7.3890561 ]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [16]:
# indexing and slicing
arr=np.array([1,2,3,4])
print(arr[0])

1


In [22]:
print(arr[::-1])
print(arr[0::2])



[4 3 2 1]
[1 3]


In [23]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(mat[0:2])
print(mat[::-1])

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [30]:
# iterating

arr=np.array([1,2,3,4,5])
for x in np.nditer(arr):
    print(x*4,end=" ")

for x in np.ndenumerate(arr):
    print("\n",x)

4 8 12 16 20 
 ((0,), 1)

 ((1,), 2)

 ((2,), 3)

 ((3,), 4)

 ((4,), 5)


In [36]:
# views vs copies

arr=np.array([1,2,3,4])
view=arr
print(view)
view[0]=9
print(view)

[1 2 3 4]
[9 2 3 4]


In [37]:
# copy
copy=arr
print(copy)
copy[0]=7
print(copy)
print(view)

[9 2 3 4]
[7 2 3 4]
[7 2 3 4]


In [38]:
print(mat.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array_split(arr1, 2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [52]:
print(np.hsplit(arr1,2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [53]:
print(np.tile(arr1,2))

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]
